public class AccountService {
//           ^ definition.class
    public AccountService() {
//         ^ definition.method
    }

    public void doProcessing(Account acc) {
//              ^ definition.method
    }
}

public interface ServiceHandler {
//               ^ definition.interface
    void execute();
//       ^ definition.method
}

public enum Status {
//          ^ definition.enum
    OPEN,
    CLOSED
}
